### PR TITLE
Graham

### PR DESCRIPTION
**Pull request by GrahamHPope**
Some docs slightly modified with collection times, etc.

### CODE REVIEW

**Comment by raelinamarie** [comment]
Look at you!

**Comment by GrahamHPope** [comment]
Jeeezzzz.... only told that we are now Gitting and no longer
BitBucketing.....

I git now :-) .... need plenty more issues to be resolved and i have found
out where you and Fab hang out.

G

On 10 August 2015 at 20:35, Raelina Marie <notifications@github.com> wrote:

> Look at you!
>
> On Mon, Aug 10, 2015 at 12:23 PM, GrahamHPope <notifications@github.com>
> wrote:
>
> > Some docs slightly modified with collection times, etc.
> > ------------------------------
> > You can view, comment on, or merge this pull request online at:
> >
> > https://github.com/F483/bikesurf.org/pull/60
> > Commit Summary
> >
> > - Update borrower_remind_dropoff_message.txt
> > - Update borrower_remind_pickup_message.txt
> > - Update borrower_respond_accepted.txt
> >
> > File Changes
> >
> > - *M*
> > apps/borrow/templates/borrow/email/borrower_remind_dropoff_message.txt
> > <https://github.com/F483/bikesurf.org/pull/60/files#diff-0> (2)
> > - *M*
> > apps/borrow/templates/borrow/email/borrower_remind_pickup_message.txt
> > <https://github.com/F483/bikesurf.org/pull/60/files#diff-1> (4)
> > - *M* apps/borrow/templates/borrow/email/borrower_respond_accepted.txt
> > <https://github.com/F483/bikesurf.org/pull/60/files#diff-2> (4)
> >
> > Patch Links:
> >
> > - https://github.com/F483/bikesurf.org/pull/60.patch
> > - https://github.com/F483/bikesurf.org/pull/60.diff
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/F483/bikesurf.org/pull/60>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/F483/bikesurf.org/pull/60#issuecomment-129559211>.
>



-- 
<http://bikesurf.org>
[image: Facebook]
<http://www.facebook.com/pages/BikeSurfBerlin/316395678456393?ref=ts> [image:
Twitter] <http://www.twitter.com/bikesurfberlin>

**Comment by raelinamarie** [comment]
Awesome, welcome aboard :)

**Comment by dcarral** [comment]
:)

**Pull request merged**
